
alias ls='ls --color=auto'
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias sshAli='ssh root@120.27.17.47'
alias gst='git status'
alias gl='git log'
alias grepflict='grep -lr "<<<<<<" .'
alias grep='grep --color=auto'
alias sc='screen'
alias god="sh dev_build.sh ; sh ./output/dev_bootstrap.sh"
alias fisdev='fisb release -w -d  dev'
alias dc='docker-compose'
alias fisclr='fisb release -c'
alias ifcfg='ifconfig | grep netmask'
alias inspector='node-inspector -p=8089'
alias ndebug='node --debug=5859 ./bin/www'
alias kpt='/Users/raku/Sites/shell_playground/killByPort.sh'
alias kdv='~/Sites/shell_playground/killDlv.sh'
alias toDocker='docker exec -it'
alias gti='git'
alias gut='git'
alias cp='cp -r'
alias j='z'
